import { inngest, type GitHubPrReceivedEvent } from "@/features/inngest/client";
import { generateReview } from "@/features/reviews/server/generate-review";
import { getPullRequestFiles } from "@/features/reviews/server/pr-files";
import { postPrComment } from "@/features/reviews/server/pr-comment";
import {
  buildPrNamespace,
  saveChunksToPinecone,
  searchPrContext,
} from "@/features/reviews/server/vectors";
import { chunkPrFiles } from "@/features/reviews/utils/chunk-code";
import { prisma } from "@/lib/db";

async function markPullRequestFailed(
  repoFullName: string,
  prNumber: number,
  errorMessage: string
) {
  await prisma.pullRequest.update({
    where: {
      repoFullName_prNumber: {
        repoFullName,
        prNumber,
      },
    },
    data: {
      status: "failed",
      reviewComment: `Review failed: ${errorMessage}`,
    },
  });
}

export const reviewPullRequest = inngest.createFunction(
  {
    id: "review-pull-request",
    retries: 3,
    triggers: [{ event: "github/pr.received" }],
    onFailure: async ({ event, error }) => {
      const originalEvent = event.data.event;
      const data = originalEvent.data as GitHubPrReceivedEvent;
      await markPullRequestFailed(
        data.repoFullName,
        data.prNumber,
        error.message ?? "Unknown error"
      );
    },
  },
  async ({ event, step }) => {
    const {
      installationId,
      repoFullName,
      prNumber,
      title,
    } = event.data;

    await step.run("mark-processing", async () => {
      await prisma.pullRequest.update({
        where: {
          repoFullName_prNumber: {
            repoFullName,
            prNumber,
          },
        },
        data: { status: "processing" },
      });
    });

    const chunks = await step.run("fetch-and-chunk", async () => {
      const files = await getPullRequestFiles(
        installationId,
        repoFullName,
        prNumber
      );
      return chunkPrFiles(prNumber, files);
    });

    if (chunks.length === 0) {
      await step.run("mark-reviewed-no-code", async () => {
        await prisma.pullRequest.update({
          where: {
            repoFullName_prNumber: {
              repoFullName,
              prNumber,
            },
          },
          data: {
            status: "reviewed",
            reviewComment:
              "No reviewable code changes found in this pull request.",
            reviewedAt: new Date(),
          },
        });
      });

      return { status: "reviewed", reason: "no-code-changes" };
    }

    const namespace = buildPrNamespace(repoFullName, prNumber);

    await step.run("save-chunks-to-pinecone", async () => {
      await saveChunksToPinecone(namespace, chunks);
    });

    await step.sleep("wait-for-pinecone-indexing", "10s");

    const contextChunks = await step.run("search-pr-context", async () => {
      return searchPrContext(namespace, title, 5);
    });

    const reviewText = await step.run("generate-review", async () => {
      return generateReview(title, contextChunks);
    });

    await step.run("post-pr-comment", async () => {
      const commentBody = `## AI Code Review\n\n${reviewText}\n\n---\n*Generated by AI Code Reviewer*`;
      await postPrComment(
        installationId,
        repoFullName,
        prNumber,
        commentBody
      );
    });

    await step.run("mark-reviewed", async () => {
      await prisma.pullRequest.update({
        where: {
          repoFullName_prNumber: {
            repoFullName,
            prNumber,
          },
        },
        data: {
          status: "reviewed",
          reviewComment: reviewText,
          reviewedAt: new Date(),
        },
      });
    });

    return { status: "reviewed", chunks: chunks.length };
  }
);
